INSERT INTO USER(EMAIL, NAME, PASSWORD) VALUES('youngjin@oneplat.co', 'DevAndy', '*1234*');
INSERT INTO QUESTION(AUTHOR, CREATED_DATE, TITLE, CONTENTS) VALUES('DevAndy', '2015-05-02', 'Hello Spring Boot', 'Hello World.');
INSERT INTO QUESTION(AUTHOR, CREATED_DATE, TITLE, CONTENTS) VALUES('DevAndy', '2015-06-02', '두번째 글', 'Hello');
INSERT INTO QUESTION(AUTHOR, CREATED_DATE, TITLE, CONTENTS) VALUES('일원동개발자', '2020-12-02', 'SpringBoot/JPA', '이게 Spring Boot와 JPA로 개발한 게시판이구나');