INSERT INTO USER(EMAIL, NAME, PASSWORD) VALUES('youngjin@google.com', 'DevAndy', '*1234*');

INSERT INTO QNA(AUTHOR_ID, AUTHOR_NAME, CONTENTS, CREATED_DATE, TITLE) VALUES('1','DevAndy', 'hello world1','2020-05-22','ONE');
INSERT INTO QNA(AUTHOR_ID, AUTHOR_NAME, CONTENTS, CREATED_DATE, TITLE) VALUES('1','DevAndy', 'hello world2','2020-07-02','TWO');
INSERT INTO QNA(AUTHOR_ID, AUTHOR_NAME, CONTENTS, CREATED_DATE, TITLE) VALUES('1','DevAndy', 'hello world3','2020-12-25','THREE');